convert 00_skap.JPG -compress none 00_SKAP.ppm
convert 01_S_ba.JPG -compress none 01_S_BA.ppm
convert 01_S_kap.JPG -compress none 01_S_kap.ppm
convert 01_St_kp.JPG -compress none 01_ST_KP.ppm
convert 01_STUB.JPG -compress none 01_STUB.ppm
convert KAMEN.JPG -compress none KAMEN.ppm
convert KAMEN-stup.JPG -compress none KAMEN-stup.ppm
convert prozor1.JPG -compress none PROZOR1.ppm
convert reljef.JPG -compress none RELJEF.ppm
convert sp_luk-bump.JPG -compress none sp_luk-bump.ppm
convert sp_luk.JPG -compress none SP_LUK.ppm
convert vrata_ko.JPG -compress none VRATA_KO.ppm
convert vrata_kr.JPG -compress none VRATA_KR.ppm
convert x01_st.JPG -compress none X01_ST.ppm
convert 01_S_kap-bump.jpg -compress none 01_S_kap-bump.ppm
convert 01_St_kp-bump.jpg -compress none 01_St_kp-bump.ppm
convert 01_STUB-bump.jpg -compress none 01_STUB-bump.ppm
convert KAMEN-bump.jpg -compress none KAMEN-bump.ppm
convert reljef-bump.jpg -compress none reljef-bump.ppm
convert x01_st-bump.jpg -compress none x01_st-bump.ppm
